[env:esp32-c3-super-mini]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.partitions = no_ota.csv
board_build.embed_files = certs/x509_crt_bundle
extra_scripts = pre:scripts/build_meta.py
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    https://github.com/colour93/astra-ui-lite-arduino.git#f38ff08d4ae8d11f2ea1ef6b0f92a845a311bef5
    https://github.com/colour93/esp-ble-config.git#58bc5e61520e5ae632885969c5bcf017574a0a35
    bblanchon/ArduinoJson @ 7.4.3
